### ISSUE TITLE
Ctrl+C causes --mode ssm to disconnect

### ISSUE THREAD

**Issue by hreeder** [hreeder/assh#3]
When you connect to an instance over SSM Session Manager, Ctrl+C will cause the session to end.

```
Starting session with SessionId: botocore-session-foo-bar
$ ^C
$
Aborted!
Cannot perform start session: read /dev/stdin: input/output error
```

**Comment by cprice404-aws** [comment]
This can be fixed by telling python to ignore SIGINT before spawning the subprocess; e.g. if you wrap your call to `subprocess.run` with a call to something like this:

```
@contextlib.contextmanager
def ignore_user_entered_signals():
    """
    Ignores user entered signals to avoid process getting killed.
    """
    signal_list = [signal.SIGINT, signal.SIGQUIT, signal.SIGTSTP]
    actual_signals = []
    for user_signal in signal_list:
        actual_signals.append(signal.signal(user_signal, signal.SIG_IGN))
    try:
        yield
    finally:
        for sig, user_signal in enumerate(signal_list):
            signal.signal(user_signal, actual_signals[sig])
```

so, like:

```
 with ignore_user_entered_signals():
    subprocess.run(...)
```

Then python will ignore the CTRL-C and allow it to pass through to the child process as desired.
```

**Comment by hreeder** [comment]
@cprice404-aws Thank you!! Just had chance to give this a test and it looks to work perfectly. I'll commit and push later today and get a bugfix release out at some point.
